import { StyleSheet } from 'react-native';
import { ColorPalette } from '../../contexts/AccessibilityContext';

export const makeStyles = (colors: ColorPalette, fontScale: number) => StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.primary,
    },
    flex: {
      flex: 1,
    },
    container: {
      flex: 1,
      alignItems: 'center',
      paddingHorizontal: 24,
      paddingTop: 15,
    },
    logo: {
      width: 200,
      height: 80,
      marginBottom: 10,
      marginTop: 30,
    },
    title: {
      fontSize: 22 * fontScale,
      fontWeight: 'bold',
      color: colors.textOnPrimary,
      marginBottom: 20,
    },
    input: {
      width: '90%',
      height: 48,
      backgroundColor: colors.inputBackground,
      color: colors.text,
      borderRadius: 8,
      paddingHorizontal: 14,
      fontSize: 16 * fontScale,
      marginBottom: 12,
      elevation: 2,
    },
    label: {
      width: '90%',
      color: colors.textOnPrimary,
      fontWeight: 'bold',
      fontSize: 16 * fontScale,
      marginBottom: 6,
      marginTop: 8,
      textAlign: 'left',
    },
    pinContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around', 
        width: '70%', 
        marginVertical: 10,
        marginBottom: 15,
    },
    pinBox: {
        width: 50,
        height: 50,
        backgroundColor: colors.inputBackground,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: colors.border,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 2,
    },
    pinText: {
        fontSize: 30 * fontScale,
        color: colors.text,
        textAlign: 'center',
    },
    pinInput: {
      width: '60%',
      height: 48,
      backgroundColor: colors.inputBackground,
      borderRadius: 8,
      paddingVertical: 10,
      fontSize: 24 * fontScale,
      letterSpacing: 15,
      textAlign: 'center',
      marginBottom: 12,
      elevation: 2,
      color: colors.text, 
    },
    keypad: {
      width: '70%',
      marginVertical: 10,
    },
    keypadRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginVertical: 5,
    },
    keypadButton: {
      width: 60,
      height: 60,
      borderRadius: 30,
      justifyContent: 'center',
      alignItems: 'center',
    },
    keypadButtonText: {
      fontSize: 28 * fontScale,
      color: colors.textOnPrimary,
      fontWeight: 'bold',
    },
    confirmButton: {
      backgroundColor: colors.primary,
      borderRadius: 8,
      marginTop: 15,
      width: '60%',
      paddingVertical: 12,
      alignItems: 'center',
      elevation: 2,
      minHeight: 48,
    },
    confirmButtonText: {
      color: colors.textOnPrimary,
      fontSize: 18 * fontScale,
      fontWeight: 'bold',
    },
});